### ISSUE TITLE
Act 2 Entrevista

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-osteas-b#1]
[ACT2 Entrevista-22620040,22620229.pdf](https://github.com/user-attachments/files/16841550/ACT2.Entrevista-22620040.22620229.pdf)

Héctor Eduardo Santiago Bautista
Josue Angel Garcia Aparicio

Actividad 2 Entrevista

**Comment by GibranVasquez** [comment]
20 una entrevista bien desarrollada y excelentemente planificada.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
